book/urls.py
from django.urls import path
from .views import(
    books_view,
    book_detail_view,
    authors_view,
    genres_view,
)

app_name = 'book'
urlpatterns = [
    path('list/', books_view, name='books'),
    path('detail/<slug:book_slug>/', book_detail_view, name='book_detail'),
    path('authors/', authors_view, name='authors'),
    path('genres/', genres_view, name='genres'),
    path('genres/<slug:genre_slug>/', books_view, name='genre_books'),
    path('authors/<slug:author_slug>/', books_view, name='author_books'),
]

core/urls.py
from ast import increment_lineno
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home, name='home'),
    path('', RedirectView.as_view(pattern_name='home')),

    path('customer/', include('customer.urls', namespace='customer')),
    path('book/', include('book.urls', namespace='book')),

    path('api/users/', include('customer.api.urls')),
    path('api/', include('book.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/api/urls.py
from django.urls import path
from .views import (
    UserCreateAPIView,
    UserListAPIView,
    UserDetailAPIView,
    UserUpdateAPIView,
    LoginAPIView,
    PasswordChangeAPIView,
    CartAPIView,
    CartAddAPIView,
    CartRemoveAPIView,
    OrderedBooksAPIView,
    OrdersAPIView,
    OrderItemsAPIView,
    FakePaymentAPIView,
)

urlpatterns = [
    path('list/', UserListAPIView.as_view()),
    path('signup/', UserCreateAPIView.as_view()),
    path('login/', LoginAPIView.as_view()),
    path('<int:id>/', UserDetailAPIView.as_view(), name='user-detail'),
    path('<int:id>/update/', UserUpdateAPIView.as_view()),
    path('<int:id>/change-password/', PasswordChangeAPIView.as_view()),

    path('<int:id>/cart/', CartAPIView.as_view(), name='cart'),
    path('<int:id>/cart/add/<slug:book_slug>/', CartAddAPIView.as_view(), ),
    path('<int:id>/cart/remove/<slug:book_slug>/', CartRemoveAPIView.as_view(), name='cart_remove'),
    path('<int:id>/cart/payment/', FakePaymentAPIView.as_view(), name='fake_payment'),
    
    path('<int:id>/books/', OrderedBooksAPIView.as_view(), name='user_books'),
    path('<int:id>/orders/', OrdersAPIView.as_view(), name='orders'),
    path('<int:id>/orders/<str:order_id>/', OrderItemsAPIView.as_view(), name='order_items'),

]


"""
    'users/' [name='user-list'] GET -> return users list (required admin user with token authentication)
    'users/<int:pk>/' [name='user-detail'] GET -> return user detail (is admin or is owner required with token authentication)
    'users/<int:pk>/' [name='user-detail'] PUT -> update user (is admin or is owner required with token authentication)
    'users/<int:pk>/' [name='user-detail'] PATCH -> partial update (is admin or is owner required with token authentication)
    'users/<int:pk>/' [name='user-detail'] DELETE -> delete user (is admin or is owner required with token authentication)
    'users/' [name='user-list'] POST -> create new staff user
    'users/login/' [name='user-login'] POST -> return user token key
    'users/<int:pk>/change_password/' [name='user-change-password'] POST -> change password (is owner required with token authentication)
    """

customer/urls.py
from django.urls import path
from .views import(
    signup_view,
    login_view,
    logout_view,
    profile_view,
    profile_update_view,
    password_update_view,
    cart_add_view,
    cart_remove_view,
    cart_view,
    checkout_view,
    fake_payment_view,
    receipt_view,
    user_books_view,
    orders_view,
    order_items_view,
)


app_name = 'customer'
urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', profile_update_view, name='profile_update'),
    path('password/update/', password_update_view, name='password_update'),

    path('cart/', cart_view, name='cart'),
    path('cart/add/<int:book_id>/', cart_add_view, name='cart_add'),
    path('cart/remove/<int:book_id>/', cart_remove_view, name='cart_remove'),

    path('cart/checkout/', checkout_view, name='checkout'),
    path('cart/payment/', fake_payment_view, name='fake_payment'),

    path('orders/receipt/<str:order_id>/', receipt_view, name='receipt'),
    path('books/', user_books_view, name='user_books'),
    path('orders/', orders_view, name='orders'),
    path('orders/items/<str:order_id>/', order_items_view, name='order_items'),

]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from uuid import uuid4
from core.utils import avatar_upload
from book.models import Book
from rest_framework.authtoken.models import Token

class Customer(models.Model):
    GENDER_CHOICES = (('Male', 'Male'),('Female', 'Female'))

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=6, blank=True, choices=GENDER_CHOICES)
    avatar = models.ImageField(upload_to=avatar_upload, default='avatars/default.png')

    @property
    def ordered_books(self):
        books = []
        completed_orders = [order for order in self.orders.all() if order.complete]
        for order in completed_orders:
            for item in order.items.all(): books.append(item.book)
        return books

    @property
    def cart(self):
        order, order_created = Order.objects.get_or_create(customer=self, complete=False)
        return order
        
    @property
    def cart_total_price(self):
        return sum([item.book.price for item in self.cart.items.all()])

    def update_cart_total_price(self):
        cart = self.cart
        cart.amount = self.cart_total_price
        cart.save()
    

    def book_status(self, book):
        if book in self.ordered_books: return 3
        elif book in [item.book for item in self.cart.items.all()]: return 2
        else: return 1

    def __str__(self) -> str:
        return self.user.username


class Order(models.Model):
    order_id = models.UUIDField(primary_key=True, default=uuid4, editable=False) # will be used for refrence code
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, related_name='orders')
    date_added = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    complete = models.BooleanField(default=False)
    dete_completed = models.DateTimeField(blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.customer.user.username} ({str(self.order_id)})'

    class Meta:
        ordering = ['-date_added']


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, related_name='items')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return f'{self.order.customer.user.username}, {self.book.title}'


# create customer object for user when new user created
# generate a token for the new user
@receiver(post_save, sender=User)
def create_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)
        Token.objects.create(user=instance)
    instance.customer.save()

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Customer


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())


class UserUpdateForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    # check that email is not duplicate
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError('A user with that email already exists.')
        return email


class CustomerUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        exclude = ['user',]

customer/api/views.py
from datetime import datetime
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from book.api.serializers import BookSerializer
from book.models import Book
from .permissions import IsAdmin, IsAdminOrOwner, IsOwner

from customer.models import OrderItem, Order
from .serializers import OrderItemSerializer, OrderSerializer, UserSerializer, LoginSerializer, PasswordChangeSerializer


class UserCreateAPIView(APIView):

    def post(self, request):
        serializer = UserSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            user = serializer.save()
            token = Token.objects.get(user=user).key
            data = {'user': serializer.data, 'token': token}
            return Response(data=data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class UserListAPIView(APIView):

    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdmin]

    def get(self, request):
        users = User.objects.all()        
        serializer = UserSerializer(users, many=True, context={'request': request})
        return Response(data=serializer.data, status=status.HTTP_200_OK)
    

class UserDetailAPIView(APIView):

    authentication_classes = [TokenAuthentication,]
    permission_classes = [IsAdminOrOwner]

    def get(self, request, **kwargs):
        user = get_object_or_404(User, id=kwargs['id'])
        self.check_object_permissions(request, user)
        serializer = UserSerializer(user, context={'request': request})
        return Response(data=serializer.data, status=status.HTTP_200_OK)


class UserUpdateAPIView(APIView):

    authentication_classes = [TokenAuthentication,]
    permission_classes = [IsAdminOrOwner]

    def put(self, request, **kwargs):
        user = get_object_or_404(User, id=kwargs['id'])
        self.check_object_permissions(request, user)
        serializer = UserSerializer(user, data=request.data, context={'request': request}, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LoginAPIView(APIView):

    def post(self, request):
        serializer = LoginSerializer(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data
        token = Token.objects.get(user=user).key
        data = {
            'id': user.id,
            'username': user.username,
            'token': token
        }
        return Response(data=data, status=status.HTTP_200_OK)


class PasswordChangeAPIView(APIView):
    
    authentication_classes = [TokenAuthentication,]
    permission_classes = [IsOwner,]

    def put(self, request, **kwargs):

        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)

        serializer = PasswordChangeSerializer(user, data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            msg = {"detail": "password changed successfully"}
            return Response(msg, status = status.HTTP_200_OK)
        
        return Response(serializer.errors, status = status.HTTP_400_BAD_REQUEST)

    def has_object_permission(self, request, view, obj):
        return request.user == obj


class CartAPIView(APIView):
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdminOrOwner]

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        # get user cart
        cart = user.customer.cart
        # get list of books in user's cart
        cart_books = [item.book for item in cart.items.all()]
        serializer = BookSerializer(cart_books, many=True, context={'request': request})
        data = {
            'order_id': cart.order_id,
            'books': serializer.data
        }
        return Response(data=data)


class FakePaymentAPIView(APIView):
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsOwner]

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        # get user cart
        order = user.customer.cart
        if order.items.all().count() == 0:
            return Response({'detail': 'ther is not any pending order.'})

        order.amount = user.customer.cart_total_price
        order.complete = True
        order.dete_completed = datetime.now()
        order.save()
        serializer = OrderSerializer(order, context={'request': request})
        return Response(serializer.data)


class CartAddAPIView(APIView):

    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated, IsOwner]

    def post(self, request, *args, **kwargs):
        # add a book to the user's cart.
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        book = get_object_or_404(Book, slug=kwargs['book_slug'])
        cart = request.user.customer.cart
        order_item, created = OrderItem.objects.get_or_create(order=cart, book=book)
        request.user.customer.update_cart_total_price()
        sr = OrderItemSerializer(order_item, context={'request': request})
        return Response(sr.data)


class CartRemoveAPIView(APIView):

    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated, IsOwner]

    def delete(self, request, *args, **kwargs):
        # delete a book from user's cart
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        book = get_object_or_404(Book, slug=kwargs['book_slug'])
        cart = request.user.customer.cart
        order_item = get_object_or_404(OrderItem, order=cart, book=book)
        order_item.delete()
        request.user.customer.update_cart_total_price()
        return Response({f'{book}': 'was deleted successfully.'}, status=status.HTTP_204_NO_CONTENT)


class OrderedBooksAPIView(APIView):
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdminOrOwner]

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        books = user.customer.ordered_books
        if not books:
            return Response({'detail': 'there is not any ordered book.'}, status=status.HTTP_204_NO_CONTENT)
        serializer = BookSerializer(books, many=True, context={'request': request})
        return Response(serializer.data)


class OrdersAPIView(APIView):
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdminOrOwner]

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        orders = Order.objects.filter(customer=user.customer)
        if not orders:
            return Response({'detail': 'there is not any order.'}, status=status.HTTP_204_NO_CONTENT)
        serializer = OrderSerializer(orders, many=True, context={'request': request})
        return Response(serializer.data)


class OrderItemsAPIView(APIView):
    
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdminOrOwner]

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['id'])
        self.check_object_permissions(request, user)
        try:
            order = get_object_or_404(Order, order_id=kwargs['order_id'])
            serializer = OrderItemSerializer(order.items.all(), many=True, context={'request': request})
            return Response(serializer.data)
        except Exception as err:
            return Response({'error': err})

templates/customer/cart.html
{% extends "base.html" %}

{% block title %}cart items{% endblock title %}

{% block content %}

    {% if cart_items|length == 0 %}
        <p>there is no item in your cart.</p>  

    {% else %}
        <table class="table">
            <tr>
                <th>#</th>
                <th>title</th>
                <th>author</th>
                <th>price</th>
                <th>remove</th>
            </tr>

            {% for book in cart_items %}
            <tr class="border-bottom">
                <td>{{ forloop.counter }}</td>
                <td>
                    <a class="link" href="{% url 'book:book_detail' book.slug %}">{{ book.title }}</a>
                </td>
                <td>{{ book.author }}</td>
                <td>{{ book.price }}$</td>
                <td>
                    <a class="link remove" href="{% url 'customer:cart_remove' book.id %}?sender=cart">
                        remove from your cart</a>
                </td>
            </tr>
            {% endfor %}
        </table>

        <a href="{% url 'customer:checkout' %}" class="btn">checkout {{ user.customer.cart_total_price }}$</a>

    {% endif %}

{% endblock content %}

templates/customer/checkout.html
{% extends "base.html" %}

{% block title %}checkout{% endblock title %}


{% block content %}
<span class="header">order summary</span>

<br><br>
<span class="title">order total price: </span>
<span>{{ user.customer.cart_total_price }}$</span>

<br><br>
<span class="title">books list: </span>

<br>
{% for book in cart_items %}
<span>{{ forloop.counter }}. {{ book.title }} ({{ book.price }}$)</span><br>
{% endfor %}

<br><br>
<a href="{% url 'customer:fake_payment' %}" class="btn">pay with card</a>

{% endblock content %}

templates/customer/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock title %}

{% block content %}
<form method="post" style="margin-bottom: .5rem;">
    {% csrf_token %}
    {% include "form.html" with form=form %}
    <button type="submit" class="btn">login</button>
</form>
<p>if you don't have account, <a href="{% url 'customer:signup' %}" class="link">signup</a> from here.</p>
{% endblock content %}

templates/customer/order_items.html
{% extends "base.html" %}

{% block title %}order items{% endblock title %}

{% block content %}

<table class="table">
    <tr>
        <th>#</th>
        <th>title</th>
        <th>author</th>
        <th>price</th>
    </tr>
    {% for item in order.items.all %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>
            <a class="link" href="{% url 'book:book_detail' item.book.slug %}">{{ item.book.title }}</a>
        </td>
        <td>{{ item.book.author }}</td>
        <td>{{ item.book.price }}$</td>

    </tr>
    {% endfor %}
</table>
{% endblock content %}

templates/customer/orders.html
{% extends "base.html" %}

{% block title %}order list{% endblock title %}

{% block content %}
    {% if orders|length == 0 %}
        <span>you have not any orders yet.</span>

    {% else %}
        <table class="table">
            <tr>
                <th>#</th>
                <th>order id (refrence code)</th>
                <th>date added</th>
                <th>amount</th>
                <th>complete</th>
                <th>date completed</th>
                <th>--</th>
            </tr>
            {% for order in orders %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ order.order_id }}</td>
                <td>{{ order.date_added }}</td>
                <td>{{ order.amount }}</td>
                <td>{{ order.complete }}</td>
                <td>{{ order.dete_completed }}</td>
                <td><a href="{% url 'customer:order_items' order.order_id %}">order items</a></td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock content %}

templates/customer/password_update.html
{% extends 'base.html' %}

{% block title %}change password{% endblock title %}

{% block content %}
<form method="post" style="margin-bottom: .5rem;">
    {% csrf_token %}
    {% include "form.html" with form=form %}
    <button type="submit" class="btn">change password</button>
</form>
{% endblock content %}

templates/customer/profile.html
{% extends "base.html" %}

{% block title %}proifle{% endblock title %}

{% block content %}
<div style="display: flex; justify-content: space-between;">

    <div class="left">
        <div style="margin-bottom: .5rem;">
            <span class="title">username:</span>
            <span>{{ user.username }}</span>
        </div>
        <div style="margin-bottom: .5rem;">
            <span class="title">email:</span>
            <span>{{ user.email }}</span>
        </div>
        <div style="margin-bottom: .5rem;">
            <span class="title">firstname:</span>
            <span>{{ user.first_name }}</span>
        </div>
        <div style="margin-bottom: .5rem;">
            <span class="title">lastname:</span>
            <span>{{ user.last_name }}</span>
        </div>
        <div style="margin-bottom: .5rem;">
            <span class="title">registration date:</span>
            <span>{{ user.date_joined }}</span>
        </div>
        <div style="margin-bottom: .5rem;">
            <span class="title">gender:</span>
            <span>{{ customer.gender }}</span>
        </div>
    </div>

    <div class="right">
        <img src="{{ customer.avatar.url }}" alt="User Avatar"
            style="height: 200px; border-radius: 40%; border: 2px solid var(--dark);">
    </div>
</div>

<a href="{% url 'customer:profile_update' %}" class="link">update profile</a><br>
<a href="{% url 'customer:password_update' %}" class="link">change password</a><br>
<a href="{% url 'customer:cart' %}" class="link">cart</a><br>
<a href="{% url 'customer:user_books' %}" class="link">ordered books</a><br>
<a href="{% url 'customer:orders' %}" class="link">orders</a>

{% endblock content %}

templates/customer/profile_update.html
{% extends "base.html" %}

{% block title %}profile update{% endblock title %}

{% block content %}
<form method="post" enctype="multipart/form-data" style="margin-bottom: .5rem;">
    {% csrf_token %}
    {% include "form.html" with form=user_form %}
    {% include "form.html" with form=customer_form %}
    <button type="submit" class="btn">update profile</button>
</form>  
{% endblock content %}

templates/customer/receipt.html
{% extends "base.html" %}

{% block title %}order receipt{% endblock title %}

{% block content %}
<span class="header">order receipt</span>

<br><br>
<span class="title">refrence code: </span>
<span>{{ order.order_id }}</span>

<br><br>
<span class="title">order added date: </span>
<span>{{ order.date_added }}</span>

<br><br>
<span class="title">order completed date: </span>
<span>{{ order.dete_completed }}</span>

<br><br>
<span class="title">order total price: </span>
<span>{{ order.amount }}</span>

<br><br>
<span class="title">ordered books: </span>
{% for order_item in order.items.all %}
<br>
<span>{{ forloop.counter }}. {{ order_item.book.title }}</span>
<a href="{{ order_item.book.pdf.url }}" class="link">download</a>  
{% endfor %}

<br><br>
<p>you can also see the download link of all the books you have purchased 
    from the <a href="{% url 'customer:user_books' %}" class="link">ordered books</a> menu</p>

{% endblock content %}

templates/customer/signup.html
{% extends 'base.html' %}

{% block title %}signup{% endblock title %}

{% block content %}
<form method="post" style="margin-bottom: .5rem;">
    {% csrf_token %}
    {% include "form.html" with form=form %}
    <button type="submit" class="btn">create account</button>
</form>
<p>if you already have an account, just <a href="{% url 'customer:login' %}" class="link">login</a>.</p>
{% endblock content %}

templates/customer/user_books.html
{% extends "base.html" %}

{% block title %}ordered books list{% endblock title %}

{% block content %}

    {% if books|length == 0 %}
        <span>you have not purchased any books yet.</span>

    {% else %}
        <table class="table">
            <tr>
                <th>#</th>
                <th>title</th>
                <th>author</th>
                <th>pages</th>
                <th>download link</th>
            </tr>
            {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a class="link" href="{% url 'book:book_detail' book.slug %}">{{ book.title }}</a>
                </td>
                <td>{{ book.author }}</td>
                <td>{{ book.pages }}</td>
                <td>
                    <a class="link" href="{{book.pdf.url}}">download</a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
  
{% endblock content %}