book/api/urls.py
from django.urls import path

from .viewsets import AuthorViewSet, GenreViewSet, BookViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'authors', AuthorViewSet, basename='author')
router.register(r'genres', GenreViewSet, basename='genre')
router.register(r'books', BookViewSet, basename='book')

author_books = BookViewSet.as_view({'get': 'author_books'})
genre_books = BookViewSet.as_view({'get': 'genre_books'})

urlpatterns = [
    path('author/<slug>/books/', author_books, name='author-books'),
    path('genre/<slug>/books/', genre_books, name='genre-books'),
]

urlpatterns += router.urls

book/urls.py
from django.urls import path
from .views import(
    books_view,
    book_detail_view,
    authors_view,
    genres_view,
)

app_name = 'book'
urlpatterns = [
    path('list/', books_view, name='books'),
    path('detail/<slug:book_slug>/', book_detail_view, name='book_detail'),
    path('authors/', authors_view, name='authors'),
    path('genres/', genres_view, name='genres'),
    path('genres/<slug:genre_slug>/', books_view, name='genre_books'),
    path('authors/<slug:author_slug>/', books_view, name='author_books'),
]

core/urls.py
from ast import increment_lineno
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home, name='home'),
    path('', RedirectView.as_view(pattern_name='home')),

    path('customer/', include('customer.urls', namespace='customer')),
    path('book/', include('book.urls', namespace='book')),

    path('api/users/', include('customer.api.urls')),
    path('api/', include('book.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from .views import(
    signup_view,
    login_view,
    logout_view,
    profile_view,
    profile_update_view,
    password_update_view,
    cart_add_view,
    cart_remove_view,
    cart_view,
    checkout_view,
    fake_payment_view,
    receipt_view,
    user_books_view,
    orders_view,
    order_items_view,
)


app_name = 'customer'
urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', profile_update_view, name='profile_update'),
    path('password/update/', password_update_view, name='password_update'),

    path('cart/', cart_view, name='cart'),
    path('cart/add/<int:book_id>/', cart_add_view, name='cart_add'),
    path('cart/remove/<int:book_id>/', cart_remove_view, name='cart_remove'),

    path('cart/checkout/', checkout_view, name='checkout'),
    path('cart/payment/', fake_payment_view, name='fake_payment'),

    path('orders/receipt/<str:order_id>/', receipt_view, name='receipt'),
    path('books/', user_books_view, name='user_books'),
    path('orders/', orders_view, name='orders'),
    path('orders/items/<str:order_id>/', order_items_view, name='order_items'),

]

book/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import FileExtensionValidator
from core.utils import book_cover_upload, pdf_upload, validate_published_year


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name='full name', unique=True)
    description = models.TextField(verbose_name='about author', blank=True, null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.name = str(self.name).lower()
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Genre(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(verbose_name='description', blank=True, null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.title = str(self.title).lower()
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title


class Book(models.Model):
    title = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(verbose_name='about book', blank=True, null=True, max_length=2000)
    pages = models.PositiveIntegerField(default=10)
    language = models.CharField(max_length=100, blank=True, null=True, default='English')
    published_year = models.PositiveSmallIntegerField(blank=True, null=True, validators=[validate_published_year])
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    cover = models.ImageField(upload_to=book_cover_upload, default='ebook_pictures/default.png')
    slug = models.SlugField(unique=True)
    pdf = models.FileField(upload_to=pdf_upload, validators=[FileExtensionValidator(['pdf'])])
    genres = models.ManyToManyField(Genre, related_name='books', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.title = str(self.title).lower()
        self.description = str(self.description).lower()
        self.language = str(self.language).lower()
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.title} by {self.author.name}'

book/api/views.py
from functools import partial
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import BasePermission, SAFE_METHODS
from django.shortcuts import get_object_or_404
from book.models import Author, Genre, Book
from .serializers import AuthorSerializer, GenreSerializer, BookSerializer


class IsAdminOrReadOnly(BasePermission):
    """
    permission to staff users to GET request
    only superuser users cat access to POST, PUT, DELETE requests
    """
    
    def has_permission(self, request, *args):
        if request.method in SAFE_METHODS: return True
        if request.user.is_superuser: return True
        return False


class AuthorAPIView(APIView):

    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAdminOrReadOnly]
    
    def get(self, request, **kwargs):
        authors = Author.objects.all()
        if 'author_slug' in kwargs:
            authors = authors.filter(slug=kwargs['author_slug'])
        serializer = AuthorSerializer(authors, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, **kwargs):
        serializer = AuthorSerializer(data=request.data, context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, **kwargs):
        author = get_object_or_404(Author, slug=kwargs['author_slug'])
        serializer = AuthorSerializer(author, data=request.data, context={'request': request}, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, **kwargs):
        author = get_object_or_404(Author, slug=kwargs['author_slug'])
        author.delete()
        msg = {'detail': f'{author} was deleted.'}
        return Response(msg, status=status.HTTP_204_NO_CONTENT)


class GenreAPIView(APIView):

    def get(self, request, **kwargs):
        genres = Genre.objects.all()
        if 'genre_slug' in kwargs:
            genres = genres.filter(slug=kwargs['genre_slug'])
        serializer = GenreSerializer(Genre.objects.all(), many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)


class BookAPIView(APIView):

    def get(self, request, **kwargs):
        books = Book.objects.all()
        book_title = request.GET.get('book_title')
        if book_title: books = books.filter(title__icontains=book_title)
        if 'book_slug' in kwargs:  books = books.filter(slug=kwargs['book_slug'])
        if 'genre_slug' in kwargs:  books = books.filter(genres__slug=kwargs['genre_slug'])
        if 'author_slug' in kwargs: books = books.filter(author__slug=kwargs['author_slug'])
        serializer = BookSerializer(books, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)



# from .views import (
#     AuthorAPIView,
#     GenreAPIView,
#     BookAPIView,
# )

# urlpatterns = [
#     path('authors/', AuthorAPIView.as_view(), name='authors-list'),
#     path('author/<slug:author_slug>/', AuthorAPIView.as_view(), name='author-detail'),
#     path('author/<slug:author_slug>/books/', BookAPIView.as_view(), name='author-books'),
#     path('author/create/', AuthorAPIView.as_view(), name='author-create'),
#     path('author/<slug:author_slug>/update/', AuthorAPIView.as_view(), name='author-update'),
#     path('genres/', GenreAPIView.as_view(), name='genres-list'),
#     path('genre/<slug:genre_slug>/', GenreAPIView.as_view(), name='genre-detail'),
#     path('', BookAPIView.as_view(), name='books-list'),
#     path('<slug:book_slug>/', BookAPIView.as_view(), name='book-detail'),
#     path('genre/<slug:genre_slug>/books/', BookAPIView.as_view(), name='genre-books'),
# ]

book/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, Genre


def books_view(request, **kwargs):
    template = 'book/books.html'
    books = Book.objects.all()
    book_title = request.GET.get('book_title')
    if book_title: books = books.filter(title__icontains=book_title)
    if 'genre_slug' in kwargs:  books = books.filter(genres__slug=kwargs['genre_slug'])
    if 'author_slug' in kwargs: books = books.filter(author__slug=kwargs['author_slug'])
    return render(request, template, {'books': books})

def book_detail_view(request, book_slug):
    template = 'book/book_detail.html'
    book = get_object_or_404(Book, slug=book_slug)
    if not request.user.is_authenticated: status = 0
    else: status = request.user.customer.book_status(book)
    return render(request, template, {'book': book, 'status': status})

def authors_view(request):
    template = 'book/authors.html'
    author_name = request.GET.get('author_name')
    if author_name: authors = Author.objects.filter(name__icontains=author_name)
    else: authors = Author.objects.all()
    return render(request, template, {'authors': authors})

def genres_view(request):
    template = 'book/genres.html'
    genre_title = request.GET.get('genre_title')
    if genre_title: genres = Genre.objects.filter(title__icontains=genre_title)
    else: genres = Genre.objects.all()
    return render(request, template, {'genres': genres})

templates/book/authors.html
{% extends "base.html" %}

{% block title %}authors list{% endblock title %}

{% block content %}

<form action="{% url 'book:authors' %}" method="get" style="margin-bottom: .5rem;">
    <input type="text" name="author_name" placeholder="search by author name" autofocus style="width: 100%;">
</form>

{% for author in authors %}
<a href="{% url 'book:author_books' author.slug %}" style="text-decoration: none; color: var(--dark);">
    <div class="box">
        <div style="margin-bottom: .5rem;">
            <span class="header">{{ author.name }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">available books: </span>
            <span>{{ author.books.count }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">about author: </span>
            {% if author.description %}
            <span>{{ author.description }}</span>
            {% else %}
            <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. At recusandae sed amet dignissimos harum
                eaque
                quo eum repellendus a neque voluptates blanditiis, incidunt, aliquid fugit sint sit, totam adipisci
                labore.</span>
            {% endif %}
        </div>
    </div>
</a>
{% endfor %}

{% endblock content %}

templates/book/book_detail.html
{% extends "base.html" %}

{% block title %}{{ book.title }} detail{% endblock title %}

{% block content %}
<div style="display: flex;">
    <div>
        <div style="margin-bottom: .5rem;">
            <span class="header">{{ book.title }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">author: </span>
            <a class="link" href="{% url 'book:author_books' book.author.slug %}">{{ book.author.name }}</a>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">price: </span>
            <span>{{ book.price }}$</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">pages: </span>
            <span>{{ book.pages }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">language: </span>
            <span>{{ book.language }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">description: </span>
            <span>{{ book.description }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">published year: </span>
            <span>{{ book.published_year }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">genres: </span>
            <span>
                {% for genre in book.genres.all %}
                <a class="link" href="{% url 'book:genre_books' genre.slug %}" style="margin-right: .5rem;">{{ genre }}</a>
                {% endfor %}
            </span>
        </div>

        <div style="margin-top: 1rem;">
            
            <!-- login -->
            {% if status == 0 %}
            <span>
                if you want to add this book to your cart first
                <a class="link" href="{% url 'customer:login' %}">login</a>
            </span>

            <!-- add to cart -->
            {% elif status == 1 %}
            <a href="{% url 'customer:cart_add' book.id %}" class="btn">add to your cart</a>

            <!-- remove from cart -->
            {% elif status == 2 %}
            <a class="btn btn-rm" href="{% url 'customer:cart_remove' book.id %}?sender=detail">remove from your cart</a>

            <!-- download book -->
            {% elif status == 3 %}
            <a class="btn" href="{{ book.pdf.url }}">download book</a>

            {% endif %}
        </div>


    </div>
    <div>
        <img src="{{ book.cover.url }}" alt="{{ book.title }} cover" style="width: 200px; height: 300px; margin-left: 2rem;">
    </div>
</div>

{% endblock content %}

templates/book/books.html
{% extends "base.html" %}

{% block title %}book list{% endblock title %}

{% block content %}

<form action="{% url 'book:books' %}" method="get" style="margin-bottom: .5rem;">
    <input type="text" name="book_title" placeholder="search by book title" autofocus style="width: 100%;">
</form>

{% for book in books %}
<a href="{% url 'book:book_detail' book.slug %}" style="text-decoration: none; color: var(--dark);">
    <div class="box" style="display: flex; justify-content: space-between;">
        <div>
            <div style="margin-bottom: .5rem;">
                <span class="title">title: </span>
                <span>{{ book.title }}</span>
            </div>
            <div style="margin-bottom: .5rem;">
                <span class="title">author: </span>
                <span>{{ book.author.name }}</span>
            </div>
            <div style="margin-bottom: .5rem;">
                <span class="title">price: </span>
                <span>{{ book.price }}$</span>
            </div>
            <div style="margin-bottom: .5rem;">
                <span class="title">pages: </span>
                <span>{{ book.pages }}</span>
            </div>
            <div style="margin-bottom: .5rem;">
                <span class="title">language: </span>
                <span>{{ book.language }}</span>
            </div>
        </div>
        <div style="height: 200px;">
            <img src="{{ book.cover.url }}" alt="{{ book.title }} cover" style="height: 200px; width: 150px;">
        </div>
    </div>
</a>
{% endfor %}
{% endblock content %}

templates/book/genres.html
{% extends "base.html" %}

{% block title %}genres list{% endblock title %}

{% block content %}

<form action="{% url 'book:genres' %}" method="get" style="margin-bottom: .5rem;">
    <input type="text" name="genre_title" placeholder="search by genre title" autofocus style="width: 100%;">
</form>

{% for genre in genres %}
<a href="{% url 'book:genre_books' genre.slug %}" style="text-decoration: none; color: var(--dark);">
    <div class="box">
        <div style="margin-bottom: .5rem;">
            <span class="header">{{ genre.title }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">Number of books in this genre: </span>
            <span>{{ genre.books.count }}</span>
        </div>

        <div style="margin-bottom: .5rem;">
            <span class="title">about genre: </span>
            {% if genre.description %}
            <span>{{ genre.description }}</span>
            {% else %}
            <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. At recusandae sed amet dignissimos harum
                eaque
                quo eum repellendus a neque voluptates blanditiis, incidunt, aliquid fugit sint sit, totam adipisci
                labore.</span>
            {% endif %}
        </div>
    </div>
</a>
{% endfor %}

{% endblock content %}