book/urls.py
from django.urls import path
from .views import(
    books_view,
    book_detail_view,
    authors_view,
    genres_view,
)

app_name = 'book'
urlpatterns = [
    path('list/', books_view, name='books'),
    path('detail/<slug:book_slug>/', book_detail_view, name='book_detail'),
    path('authors/', authors_view, name='authors'),
    path('genres/', genres_view, name='genres'),
    path('genres/<slug:genre_slug>/', books_view, name='genre_books'),
    path('authors/<slug:author_slug>/', books_view, name='author_books'),
]

core/urls.py
from ast import increment_lineno
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home, name='home'),
    path('', RedirectView.as_view(pattern_name='home')),

    path('customer/', include('customer.urls', namespace='customer')),
    path('book/', include('book.urls', namespace='book')),

    path('api/users/', include('customer.api.urls')),
    path('api/', include('book.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from .views import(
    signup_view,
    login_view,
    logout_view,
    profile_view,
    profile_update_view,
    password_update_view,
    cart_add_view,
    cart_remove_view,
    cart_view,
    checkout_view,
    fake_payment_view,
    receipt_view,
    user_books_view,
    orders_view,
    order_items_view,
)


app_name = 'customer'
urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', profile_update_view, name='profile_update'),
    path('password/update/', password_update_view, name='password_update'),

    path('cart/', cart_view, name='cart'),
    path('cart/add/<int:book_id>/', cart_add_view, name='cart_add'),
    path('cart/remove/<int:book_id>/', cart_remove_view, name='cart_remove'),

    path('cart/checkout/', checkout_view, name='checkout'),
    path('cart/payment/', fake_payment_view, name='fake_payment'),

    path('orders/receipt/<str:order_id>/', receipt_view, name='receipt'),
    path('books/', user_books_view, name='user_books'),
    path('orders/', orders_view, name='orders'),
    path('orders/items/<str:order_id>/', order_items_view, name='order_items'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <!-- load reset.css -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <!-- load main.css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>

    <!-- navbar -->

    <div class="navbar">
        <div class="wrapper">
            <a href="{% url 'home' %}">home</a>
            <a href="{% url 'book:books' %}">books</a>
            <a href="{% url 'book:authors' %}">authors</a>
            <a href="{% url 'book:genres' %}">genres</a>

            {% if user.is_authenticated %}
            <a href="{% url 'customer:cart' %}">cart</a>
            <a href="{% url 'customer:user_books' %}">ordered books</a>
            <a href="{% url 'customer:profile' %}">profile</a>
            <a href="{% url 'customer:logout' %}">logout</a>

            {% else %}
            <a href="{% url 'customer:signup' %}">signup</a>
            <a href="{% url 'customer:login' %}">login</a>

            {% endif %}
        </div>
    </div>

    <!-- message -->
    {% for message in messages %}
    <div class="message {{ message.tags }}">
        <div>{{ message }}</div>
        <div class="closebtn" onclick="this.parentElement.style.display='none';">&times;</div>
    </div>
    {% endfor %}

    <main class="wrapper">
        {% block content %}
        {% endblock content %}
    </main>

</body>

</html>

templates/form.html
{% for field in form %}
<div style="margin-bottom: .5rem;">
    <!-- label and input -->
    <label for="{{ field.id_for_label }}" style="width: 15rem; display: inline-block;">{{ field.label }} :</label>
    {{ field }}
    <!-- help text -->
    {% if field.help_text %}
    <div style="font-size: .8rem; margin-top: .5rem;">{{ field.help_text }}</div>
    {% endif %}
    <!-- error -->
    {% for error in field.errors %}
    <div style="font-size: .8rem; color: var(--red);">{{ error }}</div>
    {% endfor %}
</div>
{% endfor %}